///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RxDesktopSample
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RxDesktopSampleRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("4d57ecd5-0109-457b-a524-4bf2db888d1f")]
    public partial class RxDesktopSampleRepository : RepoGenBaseFolder
    {
        static RxDesktopSampleRepository instance = new RxDesktopSampleRepository();
        RxDesktopSampleRepositoryFolders.CalculatorAppFolder _calculator;

        /// <summary>
        /// Gets the singleton class instance representing the RxDesktopSampleRepository element repository.
        /// </summary>
        [RepositoryFolder("4d57ecd5-0109-457b-a524-4bf2db888d1f")]
        public static RxDesktopSampleRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RxDesktopSampleRepository() 
            : base("RxDesktopSampleRepository", "/", null, 0, false, "4d57ecd5-0109-457b-a524-4bf2db888d1f", ".\\RepositoryImages\\RxDesktopSampleRepository4d57ecd5.rximgres")
        {
            _calculator = new RxDesktopSampleRepositoryFolders.CalculatorAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("4d57ecd5-0109-457b-a524-4bf2db888d1f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Calculator folder.
        /// </summary>
        [RepositoryFolder("bc69952c-fe63-44a7-a4c9-c504faa23fc8")]
        public virtual RxDesktopSampleRepositoryFolders.CalculatorAppFolder Calculator
        {
            get { return _calculator; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RxDesktopSampleRepositoryFolders
    {
        /// <summary>
        /// The CalculatorAppFolder folder.
        /// </summary>
        [RepositoryFolder("bc69952c-fe63-44a7-a4c9-c504faa23fc8")]
        public partial class CalculatorAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _num7buttonInfo;
            RepoItemInfo _plusbuttonInfo;
            RepoItemInfo _num3buttonInfo;
            RepoItemInfo _equalbuttonInfo;

            /// <summary>
            /// Creates a new Calculator  folder.
            /// </summary>
            public CalculatorAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Calculator", "/winapp[@packagename='Microsoft.WindowsCalculator']", parentFolder, 30000, null, true, "bc69952c-fe63-44a7-a4c9-c504faa23fc8", "")
            {
                _num7buttonInfo = new RepoItemInfo(this, "Num7Button", ".//container[@automationid='NumberPad']/button[@automationid='num7Button']", "", 30000, null, "d4ddd735-df8c-40c0-acc0-6e2d162aa136");
                _plusbuttonInfo = new RepoItemInfo(this, "PlusButton", ".//container[@automationid='StandardOperators']/button[@automationid='plusButton']", "", 30000, null, "9f0f66c4-35fd-46a0-9e5e-8f3b5a6578e9");
                _num3buttonInfo = new RepoItemInfo(this, "Num3Button", ".//container[@automationid='NumberPad']/button[@automationid='num3Button']", "", 30000, null, "88568222-5fb3-4e0c-a656-29340c9f59cc");
                _equalbuttonInfo = new RepoItemInfo(this, "EqualButton", ".//container[@automationid='StandardOperators']/button[@automationid='equalButton']", "", 30000, null, "74fea9e6-2506-4523-bfe4-440138ff622e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bc69952c-fe63-44a7-a4c9-c504faa23fc8")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bc69952c-fe63-44a7-a4c9-c504faa23fc8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Num7Button item.
            /// </summary>
            [RepositoryItem("d4ddd735-df8c-40c0-acc0-6e2d162aa136")]
            public virtual Ranorex.Button Num7Button
            {
                get
                {
                    return _num7buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num7Button item info.
            /// </summary>
            [RepositoryItemInfo("d4ddd735-df8c-40c0-acc0-6e2d162aa136")]
            public virtual RepoItemInfo Num7ButtonInfo
            {
                get
                {
                    return _num7buttonInfo;
                }
            }

            /// <summary>
            /// The PlusButton item.
            /// </summary>
            [RepositoryItem("9f0f66c4-35fd-46a0-9e5e-8f3b5a6578e9")]
            public virtual Ranorex.Button PlusButton
            {
                get
                {
                    return _plusbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PlusButton item info.
            /// </summary>
            [RepositoryItemInfo("9f0f66c4-35fd-46a0-9e5e-8f3b5a6578e9")]
            public virtual RepoItemInfo PlusButtonInfo
            {
                get
                {
                    return _plusbuttonInfo;
                }
            }

            /// <summary>
            /// The Num3Button item.
            /// </summary>
            [RepositoryItem("88568222-5fb3-4e0c-a656-29340c9f59cc")]
            public virtual Ranorex.Button Num3Button
            {
                get
                {
                    return _num3buttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Num3Button item info.
            /// </summary>
            [RepositoryItemInfo("88568222-5fb3-4e0c-a656-29340c9f59cc")]
            public virtual RepoItemInfo Num3ButtonInfo
            {
                get
                {
                    return _num3buttonInfo;
                }
            }

            /// <summary>
            /// The EqualButton item.
            /// </summary>
            [RepositoryItem("74fea9e6-2506-4523-bfe4-440138ff622e")]
            public virtual Ranorex.Button EqualButton
            {
                get
                {
                    return _equalbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EqualButton item info.
            /// </summary>
            [RepositoryItemInfo("74fea9e6-2506-4523-bfe4-440138ff622e")]
            public virtual RepoItemInfo EqualButtonInfo
            {
                get
                {
                    return _equalbuttonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
